# Generated by Django 4.2.17 on 2024-12-09 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="指标名称"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="healthmanage.indicator",
                        verbose_name="上级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康指标分类",
                "verbose_name_plural": "健康指标分类",
                "ordering": ["parent_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="WeightScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        default="M",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                ("maxv", models.SmallIntegerField(verbose_name="BMI最大值")),
                ("score", models.SmallIntegerField(verbose_name="分数")),
            ],
            options={
                "verbose_name": "ICVD体重评估标准",
                "verbose_name_plural": "ICVD体重评估标准",
                "ordering": ["sex", "maxv"],
                "unique_together": {("sex", "maxv")},
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ssn",
                    models.CharField(max_length=18, null=True, verbose_name="身份证号"),
                ),
                ("birthday", models.DateField(verbose_name="出生日期")),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        db_index=True,
                        default="M",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="电话")),
                (
                    "province",
                    models.CharField(
                        db_index=True, default="辽宁", max_length=16, verbose_name="省"
                    ),
                ),
                (
                    "city",
                    models.CharField(default="盘锦", max_length=16, verbose_name="市"),
                ),
                (
                    "org",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=30,
                        null=True,
                        verbose_name="单位",
                    ),
                ),
                (
                    "job",
                    models.CharField(default="工人", max_length=20, verbose_name="职位"),
                ),
                (
                    "address",
                    models.CharField(
                        default=None, max_length=60, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, default=None, upload_to="", verbose_name="照片"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户名",
                    ),
                ),
            ],
            options={
                "verbose_name": "基本信息",
                "verbose_name_plural": "基本信息",
            },
        ),
        migrations.CreateModel(
            name="TCScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        default="M",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "maxv",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="总胆固醇最大值"
                    ),
                ),
                ("score", models.SmallIntegerField(verbose_name="分数")),
            ],
            options={
                "verbose_name": "ICVD血脂评估标准",
                "verbose_name_plural": "ICVD血脂评估标准",
                "ordering": ["sex", "maxv"],
                "unique_together": {("sex", "maxv")},
            },
        ),
        migrations.CreateModel(
            name="SmokeScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        default="M",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                ("smoke", models.BooleanField(verbose_name="是否吸烟")),
                ("score", models.SmallIntegerField(verbose_name="分数")),
            ],
            options={
                "verbose_name": "ICVD吸烟评估标准",
                "verbose_name_plural": "ICVD吸烟评估标准",
                "ordering": ["sex", "smoke"],
                "unique_together": {("sex", "smoke")},
            },
        ),
        migrations.CreateModel(
            name="SmokeDiabetesInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smoke",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="吸烟"
                    ),
                ),
                (
                    "smokestart",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="吸烟开始时间"
                    ),
                ),
                (
                    "drink",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="饮酒"
                    ),
                ),
                (
                    "drinkstart",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="饮酒开始时间"
                    ),
                ),
                (
                    "diabetes",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="糖尿病"
                    ),
                ),
                (
                    "diabetesstart",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="糖尿病患病时间"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户名",
                    ),
                ),
            ],
            options={
                "verbose_name": "吸烟糖尿病信息",
                "verbose_name_plural": "吸烟糖尿病信息",
            },
        ),
        migrations.CreateModel(
            name="SingleAssess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assesstype", models.CharField(max_length=30, verbose_name="评估类型")),
                ("assessname", models.CharField(max_length=30, verbose_name="评估指标")),
                ("minv", models.FloatField(verbose_name="评估指标最小值")),
                ("maxv", models.FloatField(verbose_name="评估指标最大值")),
            ],
            options={
                "verbose_name": "单项评估标准",
                "verbose_name_plural": "单项评估标准",
                "ordering": ["assesstype", "assessname", "minv"],
                "unique_together": {("assesstype", "assessname")},
            },
        ),
        migrations.CreateModel(
            name="RiskEvaluatScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        default="M",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                ("score", models.SmallIntegerField(verbose_name="分数")),
                (
                    "risk",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="风险值%"
                    ),
                ),
            ],
            options={
                "verbose_name": "ICVD十年发病风险评估标准",
                "verbose_name_plural": "ICVD十年发病风险评估标准",
                "ordering": ["sex", "score"],
                "unique_together": {("sex", "score")},
            },
        ),
        migrations.CreateModel(
            name="RiskAnalyse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk", models.CharField(max_length=254, verbose_name="风险")),
                (
                    "hmtype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthmanage.indicator",
                        verbose_name="风险类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康风险分析",
                "verbose_name_plural": "健康风险分析",
            },
        ),
        migrations.CreateModel(
            name="HealthIntervent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intervent", models.CharField(max_length=254, verbose_name="干预建议")),
                (
                    "hmtype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthmanage.indicator",
                        verbose_name="风险类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康干预建议",
                "verbose_name_plural": "健康干预建议",
            },
        ),
        migrations.CreateModel(
            name="DiabetesScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        default="M",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                ("diabetes", models.BooleanField(verbose_name="是否糖尿病")),
                ("score", models.SmallIntegerField(verbose_name="分数")),
            ],
            options={
                "verbose_name": "ICVD糖尿病评估标准",
                "verbose_name_plural": "ICVD糖尿病评估标准",
                "ordering": ["sex", "diabetes"],
                "unique_together": {("sex", "diabetes")},
            },
        ),
        migrations.CreateModel(
            name="CommonRiskScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        default="M",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                ("age", models.SmallIntegerField(verbose_name="年龄值")),
                (
                    "avgrisk",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="平均风险%"
                    ),
                ),
                (
                    "minrisk",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="最小风险%"
                    ),
                ),
            ],
            options={
                "verbose_name": "ICVD十年发病常规风险标准",
                "verbose_name_plural": "ICVD十年发病常规风险标准",
                "ordering": ["sex", "age"],
                "unique_together": {("sex", "age")},
            },
        ),
        migrations.CreateModel(
            name="BMIScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="BMI值"
                    ),
                ),
                (
                    "wtype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthmanage.indicator",
                        verbose_name="体重分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "BMI评估标准",
                "verbose_name_plural": "BMI评估标准",
                "ordering": ["bmi", "wtype"],
            },
        ),
        migrations.CreateModel(
            name="BloodPressureScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        default="M",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                ("maxv", models.SmallIntegerField(verbose_name="收缩压最大值")),
                ("score", models.SmallIntegerField(verbose_name="分数")),
            ],
            options={
                "verbose_name": "ICVD血压评估标准",
                "verbose_name_plural": "ICVD血压评估标准",
                "ordering": ["sex", "maxv"],
                "unique_together": {("sex", "maxv")},
            },
        ),
        migrations.CreateModel(
            name="AgeScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        default="M",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                ("maxv", models.SmallIntegerField(verbose_name="年龄最大值")),
                ("score", models.SmallIntegerField(verbose_name="分数")),
            ],
            options={
                "verbose_name": "ICVD年龄评估标准",
                "verbose_name_plural": "ICVD年龄评估标准",
                "ordering": ["sex", "maxv"],
                "unique_together": {("sex", "maxv")},
            },
        ),
        migrations.CreateModel(
            name="BodyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measuretime", models.DateTimeField(unique=True, verbose_name="测量时间")),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="身高(cm)"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="体重(kg)"
                    ),
                ),
                (
                    "waist",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="腰围(cm)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "身高体重信息",
                "verbose_name_plural": "身高体重信息",
                "ordering": ["user", "-measuretime"],
                "unique_together": {("user", "measuretime")},
            },
        ),
        migrations.CreateModel(
            name="BloodPressure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measuretime", models.DateTimeField(unique=True, verbose_name="测量时间")),
                ("DBP", models.SmallIntegerField(verbose_name="舒张压(mmHg)")),
                ("SBP", models.SmallIntegerField(verbose_name="收缩压(mmHg)")),
                ("HR", models.SmallIntegerField(verbose_name="心率")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "血压信息",
                "verbose_name_plural": "血压信息",
                "ordering": ["user", "-measuretime"],
                "unique_together": {("user", "measuretime")},
            },
        ),
        migrations.CreateModel(
            name="Bcholesterin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measuretime", models.DateTimeField(unique=True, verbose_name="测量时间")),
                (
                    "TC",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="总胆固醇(mmol/L)"
                    ),
                ),
                (
                    "LDL",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="低密度脂蛋白(mmol/L)"
                    ),
                ),
                (
                    "HDL",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="高密度胆固醇(mmol/L)"
                    ),
                ),
                (
                    "TG",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="甘油三酯(mmol/L)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "血脂信息",
                "verbose_name_plural": "血脂信息",
                "ordering": ["user", "-measuretime"],
                "unique_together": {("user", "measuretime")},
            },
        ),
    ]
